basePath: /
definitions:
  doctypes.HelloEndPointResponse:
    properties:
      message:
        example: Hallo!
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the documentation to a vulnerable RestApi
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Swagger VulnAPI
  version: "1.0"
paths:
  /hallo:
    get:
      description: returns greeting
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/doctypes.HelloEndPointResponse'
      summary: greets user
schemes:
- http
swagger: "2.0"
